### ISSUE TITLE
Incorrect reporting of some errors

### ISSUE THREAD

**Issue by joetesta** [willowtreeapps/wist#100]
For each of the following two cases, an error is incorrectly reported as 

```
Parsing error: mismatched input 'sub' expecting <EOF>
```

1. `sub` with non-void return

``` brightscript
sub dostuff() as Object
end sub
```

2. `print` followed with elements separated by comma

``` brightscript
sub dostuff()
  print "Restarting app", appStoreID
end sub
```

**Comment by nishtahir** [comment]
Looks like these can only be reproduced when they preceded by a valid `sub` declaration.

```brightscript
sub dummy()
end sub

sub dostuff() as Object
end sub
```

**Comment by nishtahir** [comment]
#107 should be addressing this issue. It looks like the problem was the parser bailed out early whenever it tried to complete parsing the following `sub` block.
