### ISSUE TITLE
Best way to programmatically use wist

### ISSUE THREAD

**Issue by saintberry** [willowtreeapps/wist#114]
Hey, 

I'm looking for some guidance on the best way to programmatically use wist. I've got some gulp tasks setup for building and deploying. I'd like to have another task that's used to lint code before that happens. 

I can use exec however that seems a little dirty when the code is all JavaScript. Any ideas or best practice?

Thanks!

**Comment by nishtahir** [comment]
A good example for how to do this programmatically is [Ukor](https://github.com/willowtreeapps/ukor/blob/master/lib/utils/linter.js). You want to gather a list of files and then call 

```js
cliEngine.executeOnFiles(files)
```

The CLI engine will then log all the problems that it finds.
