### ISSUE TITLE
Parse error when using trailing comma on arrays

### ISSUE THREAD

**Issue by eddiemf** [willowtreeapps/wist#117]
The following example returns a parsing error because of the trailing comma:
```
someArray = [
  1,
  2,
  3,
]
```

Here is the error:

`[wist] Parsing error: no viable alternative at input 'subinit()\nsomeArray=[\n1,\n2,\n3,\n]'`

The following example runs fine:
```
someArray = [
  1,
  2,
  3
]
```

**Comment by nishtahir** [comment]
@eddiemf Are you using Wist2? I can't seem to reproduce it with the latest version.

**Comment by eddiemf** [comment]
Actually I just installed `vscode-ide-brightscript`, I didn't imagine it would use an old version. Also, I tried updating it but it doesn't seem to be working still, probably the plugin is using another version, I'll try to find a way to override it.

Thanks for the help!

**Comment by nishtahir** [comment]
Yeah the plugin is using an older version of wist - haven't found time to update it. If you or someone is willing to help out - the wist implementation needs to be updated here https://github.com/willowtreeapps/hinoki/ This will then work with the vscode and atom plugins
