### ISSUE TITLE
Conditional Compilation Parser Support

### ISSUE THREAD

**Issue by loopyDeveloper** [willowtreeapps/wist#60]
https://forums.roku.com/viewtopic.php?t=106057

https://sdkdocs.roku.com/display/sdkdoc/Conditional+Compilation

**Comment by loopyDeveloper** [comment]
Can we update the grammar to support Conditional Compilation?

**Comment by vannuysm** [comment]
I went ahead and added a work-in-progress PR for this so we can start to shape this a bit more. I took a quick swipe at it but it's not quite there yet. Feel free to leave any comments or ideas you may have.

**Comment by nishtahir** [comment]
Fixed in #63. Closing
