### ISSUE TITLE
Naming properties inside of an associative array that collide with function names creates runtime error

### ISSUE THREAD

**Issue by nishtahir** [willowtreeapps/wist#78]
Example: 

```brightscript
AA = {
    a: 34
    b:dsd
    count:54
}
```

Attempting to invoke `AA.count()` generates a runtime error

Reference forum topic: https://forums.roku.com/viewtopic.php?f=34&t=114773

**Comment by cdthompson** [comment]
Also https://sdkdocs.roku.com/display/sdkdoc/ifEnum
