### ISSUE TITLE
Add rule: Avoid declaring argument types

### ISSUE THREAD

**Issue by cdthompson** [willowtreeapps/wist#96]
Description:

    Use 'As Dynamic' or omit parameter types to avoid runtime "Type Mismatch" exceptions. Specifying explicit types requires parameter type validation at the caller, which is more verbose than checking within the function and also prone to omission.

Explanation:

This is a pattern adopted after encountering many runtime errors.  Because BRS type coercion is incosistent, (example: invalid is ok for Object but not for Integer), we avoid type declarations in function definitions and resort to manual type checks where needed.

**Comment by nishtahir** [comment]
This should be addressed as of 383227e.
